// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEAWBq82iUV0mKX7hxsNVQfM1UZ_Fz11g',
    appId: '1:719259236347:web:176249999d6358b4c63d5e',
    messagingSenderId: '719259236347',
    projectId: 'ukk1-agil',
    authDomain: 'ukk1-agil.firebaseapp.com',
    storageBucket: 'ukk1-agil.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr2lYrAZDeMxgrqdyCeksAIEwogLug9ec',
    appId: '1:719259236347:android:1dea84a12c2f4755c63d5e',
    messagingSenderId: '719259236347',
    projectId: 'ukk1-agil',
    storageBucket: 'ukk1-agil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9iGu8c3GUeSOexqlhuI6m5l4Nxg4K_uk',
    appId: '1:719259236347:ios:eaf79fe7f307f292c63d5e',
    messagingSenderId: '719259236347',
    projectId: 'ukk1-agil',
    storageBucket: 'ukk1-agil.appspot.com',
    iosClientId: '719259236347-rnrov3978303m7pmu5di82qblk7o3c9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ukkRevisi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9iGu8c3GUeSOexqlhuI6m5l4Nxg4K_uk',
    appId: '1:719259236347:ios:eaf79fe7f307f292c63d5e',
    messagingSenderId: '719259236347',
    projectId: 'ukk1-agil',
    storageBucket: 'ukk1-agil.appspot.com',
    iosClientId: '719259236347-rnrov3978303m7pmu5di82qblk7o3c9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ukkRevisi',
  );
}
